//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KismetParser.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace KismetLanguage.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="KismetParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IKismetParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] KismetParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] KismetParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.multExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultExpr([NotNull] KismetParser.MultExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.powExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowExpr([NotNull] KismetParser.PowExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.signedAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedAtom([NotNull] KismetParser.SignedAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] KismetParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] KismetParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] KismetParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] KismetParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] KismetParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.roll_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoll_func([NotNull] KismetParser.Roll_funcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.roll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoll([NotNull] KismetParser.RollContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.die"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDie([NotNull] KismetParser.DieContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KismetParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] KismetParser.ComparisonContext context);
}
} // namespace KismetLanguage.Grammar
